# Generated by Django 4.2.5 on 2023-10-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember_unique_project_member'),
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
