# Generated by Django 4.2.7 on 2023-11-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_teammember_unique_team_member_and_more'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
