# Generated by Django 4.2.7 on 2023-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_assignment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.JSONField(),
        ),
    ]
