# Generated by Django 4.2.7 on 2023-11-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_status_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='assignmetn',
            new_name='assignment',
        ),
    ]
