# Generated by Django 4.2.7 on 2023-11-12 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_teammember_unique_team_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0006_rename_assignmetn_history_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.team'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.IntegerField(choices=[(1, 'Message'), (2, 'Assignment'), (3, 'Status'), (5, 'Title')]),
        ),
    ]
