# Generated by Django 4.2.7 on 2023-11-12 23:26

from django.db import migrations


def remove_due_date_history(apps, schema_editor):
    History = apps.get_model("issues", "History")

    History.objects.filter(type=4).delete()


def update_history_type(apps, schema_editor):
    History = apps.get_model("issues", "History")

    History.objects.filter(type=5).update(type=4)


class Migration(migrations.Migration):
    dependencies = [
        (
            "issues",
            "0007_remove_history_due_date_remove_issue_due_date_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(remove_due_date_history),
        migrations.RunPython(update_history_type),
    ]
