# Generated by Django 4.2.7 on 2023-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_auto_20231112_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.IntegerField(choices=[(1, 'Message'), (2, 'Assignment'), (3, 'Status'), (4, 'Title')]),
        ),
    ]
