# Generated by Django 4.2.5 on 2023-10-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember_unique_project_member'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teammember',
            name='unique_team_member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.AddField(
            model_name='teammember',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmember'),
            preserve_default=False,
        ),
    ]
