# Generated by Django 4.2.5 on 2023-10-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_teammember_user_teammember_member'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'member'), name='unique_team_member'),
        ),
    ]
