# Generated by Django 4.2.7 on 2023-11-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_teammember_unique_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
